# Generated by Django 2.2.6 on 2019-10-18 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('horarios_de_atendimento', models.CharField(max_length=1000)),
                ('logo', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=5000)),
                ('foto', models.CharField(max_length=300)),
                ('ingredientes', models.CharField(max_length=7000)),
                ('tabela_nutricional', models.CharField(max_length=7000)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fornecedores.Fornecedor')),
            ],
        ),
    ]
