# Generated by Django 2.2.6 on 2019-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='logo',
            field=models.CharField(max_length=5000),
        ),
    ]
