# Generated by Django 2.2.6 on 2019-10-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0002_auto_20191018_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.CharField(max_length=5000),
        ),
    ]
