# Generated by Django 2.2.6 on 2019-10-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0003_auto_20191018_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
