# Generated by Django 2.2.6 on 2019-10-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0004_produto_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='patologias',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
