# Generated by Django 2.2.6 on 2019-10-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=150)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
